#!/usr/bin/env tsx
/**
 * Memory Consolidation Script
 *
 * Purpose:
 * 1. Review recent daily memory files (last ~2 weeks)
 * 2. Extract significant insights
 * 3. Update MEMORY.md with distilled learnings (preserving any pre-existing header/notes)
 * 4. Archive older daily memory files (keep recent ones in place for OpenClaw context loading)
 */

import * as fs from 'fs';
import * as path from 'path';

const WORKSPACE_DIR = '/Users/alfredpennyworth/.openclaw/workspace';

// OpenClaw convention (see AGENTS.md): memory/YYYY-MM-DD.md
const MEMORY_DIR = path.join(WORKSPACE_DIR, 'memory');
const DAILY_FILE_RE = /^\d{4}-\d{2}-\d{2}\.md$/;

const LONG_TERM_MEMORY = path.join(WORKSPACE_DIR, 'MEMORY.md');
const ARCHIVE_DIR = path.join(MEMORY_DIR, 'archives');

const KEEP_RECENT_DAYS = 14;

// Ensure archive directory exists
if (!fs.existsSync(ARCHIVE_DIR)) {
  fs.mkdirSync(ARCHIVE_DIR, { recursive: true });
}

function listDailyMemoryFiles(): string[] {
  if (!fs.existsSync(MEMORY_DIR)) return [];

  return fs
    .readdirSync(MEMORY_DIR, { withFileTypes: true })
    .filter((d) => d.isFile() && DAILY_FILE_RE.test(d.name))
    .map((d) => d.name)
    .sort();
}

// Extract significant insights
function extractSignificantInsights(memoryContents: string[]): string[] {
  const insights: string[] = [];

  memoryContents.forEach((content) => {
    const significantSections = [
      // Look for specific markers of important content
      '### Key Decisions',
      '### Lessons Learned',
      '### Technical Challenges',
      '### What We Built',
      '### Priorities',
      '### Context for Future Sessions',
    ];

    significantSections.forEach((section) => {
      const sectionMatch = content.match(
        new RegExp(`${section}([\\s\\S]*?)(?=###|$)`, 'i')
      );

      if (sectionMatch?.[1]) {
        const body = sectionMatch[1].trim();
        if (body) insights.push(body);
      }
    });
  });

  return insights;
}

const AUTO_FOOTER_RE = /\n*---\n\n\*This file is automatically generated during memory consolidation\.\*\n\*Manual edits may be overwritten\.\*\s*$/;
const AUTO_FOOTER_TEXT =
  '*This file is automatically generated during memory consolidation.*\n' +
  '*Manual edits may be overwritten.*';

function splitExistingLongTermMemory(): { prefix: string; history: string } {
  if (!fs.existsSync(LONG_TERM_MEMORY)) {
    return { prefix: '# Long-Term Memory Archive', history: '' };
  }

  // Trim end so our footer-stripping and concatenation behave predictably.
  const existingRaw = fs.readFileSync(LONG_TERM_MEMORY, 'utf-8').trimEnd();
  const existing = existingRaw.replace(AUTO_FOOTER_RE, '').trimEnd();

  // Preserve everything before the first consolidation block (critical rules / hand-written notes).
  const idx = existing.indexOf('## Memory Consolidation:');
  if (idx < 0) {
    return { prefix: existing || '# Long-Term Memory Archive', history: '' };
  }

  const prefix = (existing.slice(0, idx).trimEnd() || '# Long-Term Memory Archive');
  const history = existing.slice(idx).trimStart();

  return { prefix, history };
}

// Update long-term memory file
function updateLongTermMemory(insights: string[]) {
  const timestamp = new Date().toISOString();
  const { prefix, history } = splitExistingLongTermMemory();

  const consolidatedBlock = `## Memory Consolidation: ${timestamp}\n\n${
    insights.length
      ? insights.map((insight) => `### Insight\n${insight}`).join('\n\n')
      : '*(No significant insights found in recent daily notes.)*'
  }`;

  const out = `${prefix}\n\n${consolidatedBlock}\n\n---\n\n${history ? `${history}\n\n---\n\n` : ''}${AUTO_FOOTER_TEXT}\n`;
  fs.writeFileSync(LONG_TERM_MEMORY, out);
}

// Archive older daily memory files (keep recent ones in place)
function archiveOldDailyFiles(allDailyFilesSorted: string[]) {
  const cutoff = Math.max(0, allDailyFilesSorted.length - KEEP_RECENT_DAYS);
  const oldFiles = allDailyFilesSorted.slice(0, cutoff);

  oldFiles.forEach((filename) => {
    const sourcePath = path.join(MEMORY_DIR, filename);
    const year = filename.slice(0, 4);
    const archivePath = path.join(ARCHIVE_DIR, year, filename);

    fs.mkdirSync(path.dirname(archivePath), { recursive: true });

    // Move file to archive
    fs.renameSync(sourcePath, archivePath);
  });

  return oldFiles;
}

function main() {
  console.log('🧠 Starting Memory Consolidation');
  console.log(`Scanning daily notes in: ${MEMORY_DIR}`);

  try {
    const dailyFiles = listDailyMemoryFiles();

    if (dailyFiles.length === 0) {
      console.log('No daily memory files to process.');
      return;
    }

    const recentFiles = dailyFiles.slice(-KEEP_RECENT_DAYS);

    const memoryContents = recentFiles.map((file) => {
      const filePath = path.join(MEMORY_DIR, file);
      return fs.readFileSync(filePath, 'utf-8');
    });

    const insights = extractSignificantInsights(memoryContents);

    console.log(`Recent files considered: ${recentFiles.length}`);
    console.log(`Extracted ${insights.length} significant insights`);

    updateLongTermMemory(insights);

    const archived = archiveOldDailyFiles(dailyFiles);
    if (archived.length) {
      console.log(`Archived ${archived.length} old daily notes to: ${ARCHIVE_DIR}`);
    } else {
      console.log('No old daily notes to archive.');
    }

    console.log('✅ Memory consolidation complete');
  } catch (error) {
    console.error('❌ Memory consolidation failed:', error);
    process.exit(1);
  }
}

main();
