#!/usr/bin/env tsx
/**
 * Memory Consolidation Script
 * 
 * Purpose: 
 * 1. Review daily memory files
 * 2. Extract significant insights
 * 3. Update MEMORY.md with distilled learnings
 * 4. Archive or remove outdated memory files
 */

import * as fs from 'fs';
import * as path from 'path';

const WORKSPACE_DIR = '/Users/alfredpennyworth/.openclaw/workspace';
const MEMORY_DIR = path.join(WORKSPACE_DIR, 'memory', 'daily');
const LONG_TERM_MEMORY = path.join(WORKSPACE_DIR, 'MEMORY.md');
const ARCHIVE_DIR = path.join(WORKSPACE_DIR, 'memory', 'archives');

// Ensure archive directory exists
if (!fs.existsSync(ARCHIVE_DIR)) {
  fs.mkdirSync(ARCHIVE_DIR, { recursive: true });
}

// Read and parse daily memory files
function readDailyMemoryFiles(): string[] {
  const files = fs.readdirSync(MEMORY_DIR)
    .filter(file => file.endsWith('.md') && file !== '.gitkeep')
    .sort()
    .slice(0, 14); // Keep last two weeks of files

  return files.map(file => {
    const filePath = path.join(MEMORY_DIR, file);
    return fs.readFileSync(filePath, 'utf-8');
  });
}

// Extract significant insights
function extractSignificantInsights(memoryContents: string[]): string[] {
  const insights: string[] = [];

  memoryContents.forEach(content => {
    const significantSections = [
      // Look for specific markers of important content
      '### Key Decisions',
      '### Lessons Learned',
      '### Technical Challenges',
      '### What We Built',
      '### Priorities',
      '### Context for Future Sessions'
    ];

    significantSections.forEach(section => {
      const sectionMatch = content.match(new RegExp(`${section}([\\s\\S]*?)(?=###|$)`, 'i'));
      
      if (sectionMatch && sectionMatch[1]) {
        insights.push(sectionMatch[1].trim());
      }
    });
  });

  return insights;
}

// Update long-term memory file
function updateLongTermMemory(insights: string[]) {
  const timestamp = new Date().toISOString();
  
  const consolidatedMemory = `# Long-Term Memory Archive

## Memory Consolidation: ${timestamp}

${insights.map(insight => `### Insight
${insight}`).join('\n\n')}

---

*This file is automatically generated during memory consolidation.*
*Manual edits may be overwritten.*`;

  fs.writeFileSync(LONG_TERM_MEMORY, consolidatedMemory);
}

// Archive processed memory files
function archiveMemoryFiles(files: string[]) {
  files.forEach((filename, index) => {
    const sourcePath = path.join(MEMORY_DIR, filename);
    const archivePath = path.join(ARCHIVE_DIR, `${new Date().getFullYear()}`, filename);
    
    // Ensure year directory exists
    fs.mkdirSync(path.dirname(archivePath), { recursive: true });
    
    // Move file to archive
    fs.renameSync(sourcePath, archivePath);
  });
}

function main() {
  console.log('🧠 Starting Memory Consolidation');
  console.log(`Processing files in: ${MEMORY_DIR}`);

  try {
    const dailyMemoryFiles = fs.readdirSync(MEMORY_DIR)
      .filter(file => file.endsWith('.md') && file !== '.gitkeep')
      .sort()
      .slice(0, 14); // Keep last two weeks of files

    if (dailyMemoryFiles.length === 0) {
      console.log('No memory files to process.');
      return;
    }

    const memoryContents = dailyMemoryFiles.map(file => {
      const filePath = path.join(MEMORY_DIR, file);
      return fs.readFileSync(filePath, 'utf-8');
    });

    const insights = extractSignificantInsights(memoryContents);
    
    console.log(`Extracted ${insights.length} significant insights`);

    updateLongTermMemory(insights);
    archiveMemoryFiles(dailyMemoryFiles);

    console.log('✅ Memory consolidation complete');
  } catch (error) {
    console.error('❌ Memory consolidation failed:', error);
    process.exit(1);
  }
}

main();